// ============================================================
// plugin.mjs - installs the launch hook into the coding tools, and edits no configuration.
//
// WHY A HOOK AT ALL
//   The shim raises a notice at launch, but only when the shim runs, and that needs the shim
//   directory first on PATH. A person who keeps their own `claude` wrapper never sees it. A hook
//   runs inside the tool, so it reports whatever the launcher is.
//
// WHY NOTHING IS EDITED
//   Claude Code loads any folder under a skills directory that holds `.claude-plugin/plugin.json`
//   as a plugin, on the next session, with no marketplace and no install step. Codex loads
//   `$CODEX_HOME/hooks.json` by itself. So each tool reads a file of its own, and `settings.json`
//   and `config.toml` are never opened.
//
// WHY IT IS OPT-IN
//   The notice is a reminder, not a part of the routing. A person who does not want it installs
//   nothing and loses nothing: the traffic still goes through the gateway, and the shim toast
//   still fires.
// ============================================================

import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { fileURLToPath } from 'node:url';

const HOOK_SCRIPT = path.join(path.dirname(fileURLToPath(import.meta.url)), 'hook-status.mjs');

export const PLUGIN_NAME = 'llm-switcher-status';
// Written into every file this module owns, and the only thing that authorizes an overwrite.
const MARK = 'Generated by LLM Switcher - safe to delete';
// A fresh start and a resumed session. A resume is the case the switcher exists for, and compact
// is left out on purpose: the notice belongs at the start of a session, not in the middle of one.
const SESSION_SOURCES = 'startup|resume';

export function claudeSkillsDir(env = process.env, home = os.homedir()) {
  return path.join(env.CLAUDE_CONFIG_DIR || path.join(home, '.claude'), 'skills');
}
export function codexHome(env = process.env, home = os.homedir()) {
  return env.CODEX_HOME || path.join(home, '.codex');
}
// The global customization root of the Antigravity CLI.
export function agyHome(home = os.homedir()) {
  return path.join(home, '.gemini', 'antigravity-cli');
}

export function renderClaudePlugin(version = 'dev') {
  return `${JSON.stringify({
    name: PLUGIN_NAME,
    version,
    description: 'Reports at the start of a session when LLM Switcher routes this tool to another provider.',
    author: { name: 'LLM Switcher' }
  }, null, 2)}\n`;
}

// The args form, not one command string: a Windows path holds backslashes and spaces, and this
// way no shell has to quote it.
export function renderClaudeHooks() {
  return `${JSON.stringify({
    description: MARK,
    hooks: {
      SessionStart: [{
        matcher: SESSION_SOURCES,
        hooks: [{ type: 'command', command: 'node', args: [HOOK_SCRIPT, 'claude'], timeout: 10 }]
      }]
    }
  }, null, 2)}\n`;
}

// Codex takes one command string. It is quoted here, once, for the same reason.
export function renderCodexHooks() {
  return `${JSON.stringify({ description: MARK, hooks: { SessionStart: [codexEntry()] } }, null, 2)}\n`;
}

function codexEntry() {
  return {
    matcher: SESSION_SOURCES,
    hooks: [{ type: 'command', command: `node "${HOOK_SCRIPT}" codex`, timeout: 10 }]
  };
}

// Ours is the entry that runs our script. Nothing else in the file is touched, by any operation.
const isOurs = (group) => JSON.stringify(group).includes('hook-status.mjs');

function writeAtomic(file, content) {
  const tmp = `${file}.${process.pid}.tmp`;
  fs.mkdirSync(path.dirname(file), { recursive: true });
  try {
    fs.writeFileSync(tmp, content, 'utf8');
    fs.renameSync(tmp, file);
  } catch (err) {
    fs.rmSync(tmp, { force: true });
    throw err;
  }
}

function readJsonFile(file) {
  if (!fs.existsSync(file)) return { missing: true };
  const raw = fs.readFileSync(file, 'utf8');
  try { return { value: JSON.parse(raw) }; } catch (err) { return { error: err.message }; }
}

// ---- Claude Code -----------------------------------------------------------------------------

function pluginDir(opts) {
  return path.join(opts.claudeSkillsDir || claudeSkillsDir(), PLUGIN_NAME);
}

function installClaude(opts, version) {
  const dir = pluginDir(opts);
  const manifest = path.join(dir, '.claude-plugin', 'plugin.json');
  // A folder with a manifest that is not ours belongs to someone else, whatever its name is.
  if (fs.existsSync(manifest)) {
    const cur = readJsonFile(manifest);
    if (cur.error) return { ok: false, reason: `${manifest} does not parse: ${cur.error}` };
    if (cur.value?.name !== PLUGIN_NAME) {
      return { ok: false, reason: `${dir} holds another plugin (${cur.value?.name}), so nothing was changed` };
    }
  }
  writeAtomic(manifest, renderClaudePlugin(version));
  writeAtomic(path.join(dir, 'hooks', 'hooks.json'), renderClaudeHooks());
  return { ok: true, path: dir };
}

function uninstallClaude(opts) {
  const dir = pluginDir(opts);
  const manifest = path.join(dir, '.claude-plugin', 'plugin.json');
  if (!fs.existsSync(manifest)) return { ok: true, path: dir, absent: true };
  const cur = readJsonFile(manifest);
  if (cur.value?.name !== PLUGIN_NAME) return { ok: false, reason: `${dir} is not our plugin, so nothing was removed` };
  fs.rmSync(dir, { recursive: true, force: true });
  return { ok: true, path: dir };
}

// ---- Codex -----------------------------------------------------------------------------------

function codexHooksPath(opts) {
  return path.join(opts.codexHome || codexHome(), 'hooks.json');
}

// The file may already hold the hooks of this machine, so it is merged, never replaced. A file
// that does not parse is left exactly as it is: it can hold work that no backup would return.
function installCodex(opts) {
  const file = codexHooksPath(opts);
  const cur = readJsonFile(file);
  if (cur.error) return { ok: false, reason: `${file} does not parse: ${cur.error}, so nothing was changed` };
  if (cur.missing) {
    writeAtomic(file, renderCodexHooks());
    return { ok: true, path: file };
  }
  const doc = cur.value && typeof cur.value === 'object' ? cur.value : {};
  doc.hooks = doc.hooks && typeof doc.hooks === 'object' ? doc.hooks : {};
  const groups = Array.isArray(doc.hooks.SessionStart) ? doc.hooks.SessionStart : [];
  doc.hooks.SessionStart = [...groups.filter(g => !isOurs(g)), codexEntry()];
  writeAtomic(file, `${JSON.stringify(doc, null, 2)}\n`);
  return { ok: true, path: file };
}

function uninstallCodex(opts) {
  const file = codexHooksPath(opts);
  const cur = readJsonFile(file);
  if (cur.missing) return { ok: true, path: file, absent: true };
  if (cur.error) return { ok: false, reason: `${file} does not parse: ${cur.error}, so nothing was changed` };
  const doc = cur.value && typeof cur.value === 'object' ? cur.value : {};
  const groups = Array.isArray(doc.hooks?.SessionStart) ? doc.hooks.SessionStart : [];
  const kept = groups.filter(g => !isOurs(g));
  if (kept.length) doc.hooks.SessionStart = kept;
  else delete doc.hooks?.SessionStart;
  // Only a file that holds nothing but our own mark is removed. Anything else is written back.
  const empty = doc.hooks && Object.keys(doc.hooks).length === 0;
  if (empty && doc.description === MARK) {
    fs.rmSync(file, { force: true });
    return { ok: true, path: file };
  }
  writeAtomic(file, `${JSON.stringify(doc, null, 2)}\n`);
  return { ok: true, path: file };
}

// ---- Antigravity CLI (agy) -------------------------------------------------------------------
//
// agy reads hooks.json from its customization root: one key per named hook. It runs a hook command
// with its quotes kept literally, so the path goes unquoted, with forward slashes. A path with a
// space cannot be written that way, and then agy is skipped.
//
// agy 1.2.14 loads this global file but does not run its hooks; only a workspace's .agents/hooks.json
// runs (measured 2026-10-03). The entry is ready for a release that runs global hooks. Until then the
// shim toast is the launch notice for agy.
export const AGY_HOOK_NAME = 'llm-switcher-status';
export const AGY_GLOBAL_HOOKS_NOTE = 'agy 1.2.14 loads global hooks but does not run them yet; the shim toast is the notice';

function agyHooksPath(opts) {
  return path.join(opts.agyHome || agyHome(), 'hooks.json');
}

export function agyHookCommand(script = HOOK_SCRIPT) {
  const p = script.split(path.sep).join('/');
  return /\s/.test(p) ? null : `node ${p} agy`;
}

const isPlainObject = (v) => Boolean(v) && typeof v === 'object' && !Array.isArray(v);

// A space in the path is a limit of agy, not a fault: the install is skipped, never failed.
function installAgy(opts) {
  const script = opts.hookScript || HOOK_SCRIPT;
  const command = agyHookCommand(script);
  if (!command) return { ok: true, skipped: true, reason: `${script} holds a space, and agy cannot run a quoted path` };
  const file = agyHooksPath(opts);
  const cur = readJsonFile(file);
  if (cur.error) return { ok: false, reason: `${file} does not parse: ${cur.error}, so nothing was changed` };
  if (!cur.missing && !isPlainObject(cur.value)) return { ok: false, reason: `${file} does not hold a JSON object, so nothing was changed` };
  const doc = cur.missing ? {} : cur.value;
  doc[AGY_HOOK_NAME] = { SessionStart: [{ type: 'command', command, timeout: 10 }] };
  writeAtomic(file, `${JSON.stringify(doc, null, 2)}\n`);
  return { ok: true, path: file };
}

function uninstallAgy(opts) {
  const file = agyHooksPath(opts);
  const cur = readJsonFile(file);
  if (cur.missing) return { ok: true, path: file, absent: true };
  if (cur.error) return { ok: false, reason: `${file} does not parse: ${cur.error}, so nothing was changed` };
  // install never writes into such a file, so the hook cannot be in it.
  if (!isPlainObject(cur.value)) return { ok: true, path: file, absent: true };
  const doc = cur.value;
  if (!Object.hasOwn(doc, AGY_HOOK_NAME)) return { ok: true, path: file, absent: true };
  delete doc[AGY_HOOK_NAME];
  // agy has no room for a mark in this file, so it is removed only when nothing else is left in it.
  if (Object.keys(doc).length === 0) fs.rmSync(file, { force: true });
  else writeAtomic(file, `${JSON.stringify(doc, null, 2)}\n`);
  return { ok: true, path: file };
}

// ---- The three commands ----------------------------------------------------------------------

// Each tool runs on its own: a fault in one file must not stop the other tools.
function summarize(steps) {
  const out = { installed: [], skipped: [], failed: [], paths: {} };
  for (const [tool, step] of Object.entries(steps)) {
    let r;
    try { r = step(); } catch (err) { r = { ok: false, reason: err.message }; }
    if (r.skipped) out.skipped.push({ tool, reason: r.reason });
    else if (r.ok) out.installed.push(tool);
    else out.failed.push({ tool, reason: r.reason });
    if (r.path) out.paths[tool] = r.path;
  }
  return out;
}

/** { installed: ['claude','codex','agy'], skipped: [{ tool, reason }], failed: [{ tool, reason }], paths } */
export function installPlugin(opts = {}, version = 'dev') {
  return summarize({ claude: () => installClaude(opts, version), codex: () => installCodex(opts), agy: () => installAgy(opts) });
}

export function uninstallPlugin(opts = {}) {
  return summarize({ claude: () => uninstallClaude(opts), codex: () => uninstallCodex(opts), agy: () => uninstallAgy(opts) });
}

export function pluginStatus(opts = {}) {
  const dir = pluginDir(opts);
  const claudeManifest = readJsonFile(path.join(dir, '.claude-plugin', 'plugin.json'));
  const file = codexHooksPath(opts);
  const codexDoc = readJsonFile(file);
  const codexGroups = Array.isArray(codexDoc.value?.hooks?.SessionStart) ? codexDoc.value.hooks.SessionStart : [];
  const agyDoc = readJsonFile(agyHooksPath(opts));
  return {
    claude: { installed: claudeManifest.value?.name === PLUGIN_NAME, path: dir, id: `${PLUGIN_NAME}@skills-dir` },
    codex: { installed: codexGroups.some(isOurs), path: file },
    agy: {
      installed: isPlainObject(agyDoc.value) && Boolean(agyDoc.value[AGY_HOOK_NAME]),
      path: agyHooksPath(opts),
      note: AGY_GLOBAL_HOOKS_NOTE,
      ...(agyDoc.error ? { error: `does not parse: ${agyDoc.error}` }
        : !agyDoc.missing && !isPlainObject(agyDoc.value) ? { error: 'does not hold a JSON object' } : {})
    }
  };
}
