// ============================================================
// plugin.mjs - installs the launch hook into the two coding tools, and edits no configuration.
//
// WHY A HOOK AT ALL
//   The shim raises a notice at launch, but only when the shim runs, and that needs the shim
//   directory first on PATH. A person who keeps their own `claude` wrapper never sees it. A hook
//   runs inside the tool, so it reports whatever the launcher is.
//
// WHY NOTHING IS EDITED
//   Claude Code loads any folder under a skills directory that holds `.claude-plugin/plugin.json`
//   as a plugin, on the next session, with no marketplace and no install step. Codex loads
//   `$CODEX_HOME/hooks.json` by itself. So each tool reads a file of its own, and `settings.json`
//   and `config.toml` are never opened.
//
// WHY IT IS OPT-IN
//   The notice is a reminder, not a part of the routing. A person who does not want it installs
//   nothing and loses nothing: the traffic still goes through the gateway, and the shim toast
//   still fires.
// ============================================================

import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { fileURLToPath } from 'node:url';

const HOOK_SCRIPT = path.join(path.dirname(fileURLToPath(import.meta.url)), 'hook-status.mjs');

export const PLUGIN_NAME = 'llm-switcher-status';
// Written into every file this module owns, and the only thing that authorizes an overwrite.
const MARK = 'Generated by LLM Switcher - safe to delete';
// A fresh start and a resumed session. A resume is the case the switcher exists for, and compact
// is left out on purpose: the notice belongs at the start of a session, not in the middle of one.
const SESSION_SOURCES = 'startup|resume';

export function claudeSkillsDir(env = process.env, home = os.homedir()) {
  return path.join(env.CLAUDE_CONFIG_DIR || path.join(home, '.claude'), 'skills');
}
export function codexHome(env = process.env, home = os.homedir()) {
  return env.CODEX_HOME || path.join(home, '.codex');
}

export function renderClaudePlugin(version = 'dev') {
  return `${JSON.stringify({
    name: PLUGIN_NAME,
    version,
    description: 'Reports at the start of a session when LLM Switcher routes this tool to another provider.',
    author: { name: 'LLM Switcher' }
  }, null, 2)}\n`;
}

// The args form, not one command string: a Windows path holds backslashes and spaces, and this
// way no shell has to quote it.
export function renderClaudeHooks() {
  return `${JSON.stringify({
    description: MARK,
    hooks: {
      SessionStart: [{
        matcher: SESSION_SOURCES,
        hooks: [{ type: 'command', command: 'node', args: [HOOK_SCRIPT, 'claude'], timeout: 10 }]
      }]
    }
  }, null, 2)}\n`;
}

// Codex takes one command string. It is quoted here, once, for the same reason.
export function renderCodexHooks() {
  return `${JSON.stringify({ description: MARK, hooks: { SessionStart: [codexEntry()] } }, null, 2)}\n`;
}

function codexEntry() {
  return {
    matcher: SESSION_SOURCES,
    hooks: [{ type: 'command', command: `node "${HOOK_SCRIPT}" codex`, timeout: 10 }]
  };
}

// Ours is the entry that runs our script. Nothing else in the file is touched, by any operation.
const isOurs = (group) => JSON.stringify(group).includes('hook-status.mjs');

function writeAtomic(file, content) {
  const tmp = `${file}.${process.pid}.tmp`;
  fs.mkdirSync(path.dirname(file), { recursive: true });
  try {
    fs.writeFileSync(tmp, content, 'utf8');
    fs.renameSync(tmp, file);
  } catch (err) {
    fs.rmSync(tmp, { force: true });
    throw err;
  }
}

function readJsonFile(file) {
  if (!fs.existsSync(file)) return { missing: true };
  const raw = fs.readFileSync(file, 'utf8');
  try { return { value: JSON.parse(raw) }; } catch (err) { return { error: err.message }; }
}

// ---- Claude Code -----------------------------------------------------------------------------

function pluginDir(opts) {
  return path.join(opts.claudeSkillsDir || claudeSkillsDir(), PLUGIN_NAME);
}

function installClaude(opts, version) {
  const dir = pluginDir(opts);
  const manifest = path.join(dir, '.claude-plugin', 'plugin.json');
  // A folder with a manifest that is not ours belongs to someone else, whatever its name is.
  if (fs.existsSync(manifest)) {
    const cur = readJsonFile(manifest);
    if (cur.error) return { ok: false, reason: `${manifest} does not parse: ${cur.error}` };
    if (cur.value?.name !== PLUGIN_NAME) {
      return { ok: false, reason: `${dir} holds another plugin (${cur.value?.name}), so nothing was changed` };
    }
  }
  writeAtomic(manifest, renderClaudePlugin(version));
  writeAtomic(path.join(dir, 'hooks', 'hooks.json'), renderClaudeHooks());
  return { ok: true, path: dir };
}

function uninstallClaude(opts) {
  const dir = pluginDir(opts);
  const manifest = path.join(dir, '.claude-plugin', 'plugin.json');
  if (!fs.existsSync(manifest)) return { ok: true, path: dir, absent: true };
  const cur = readJsonFile(manifest);
  if (cur.value?.name !== PLUGIN_NAME) return { ok: false, reason: `${dir} is not our plugin, so nothing was removed` };
  fs.rmSync(dir, { recursive: true, force: true });
  return { ok: true, path: dir };
}

// ---- Codex -----------------------------------------------------------------------------------

function codexHooksPath(opts) {
  return path.join(opts.codexHome || codexHome(), 'hooks.json');
}

// The file may already hold the hooks of this machine, so it is merged, never replaced. A file
// that does not parse is left exactly as it is: it can hold work that no backup would return.
function installCodex(opts) {
  const file = codexHooksPath(opts);
  const cur = readJsonFile(file);
  if (cur.error) return { ok: false, reason: `${file} does not parse: ${cur.error}, so nothing was changed` };
  if (cur.missing) {
    writeAtomic(file, renderCodexHooks());
    return { ok: true, path: file };
  }
  const doc = cur.value && typeof cur.value === 'object' ? cur.value : {};
  doc.hooks = doc.hooks && typeof doc.hooks === 'object' ? doc.hooks : {};
  const groups = Array.isArray(doc.hooks.SessionStart) ? doc.hooks.SessionStart : [];
  doc.hooks.SessionStart = [...groups.filter(g => !isOurs(g)), codexEntry()];
  writeAtomic(file, `${JSON.stringify(doc, null, 2)}\n`);
  return { ok: true, path: file };
}

function uninstallCodex(opts) {
  const file = codexHooksPath(opts);
  const cur = readJsonFile(file);
  if (cur.missing) return { ok: true, path: file, absent: true };
  if (cur.error) return { ok: false, reason: `${file} does not parse: ${cur.error}, so nothing was changed` };
  const doc = cur.value && typeof cur.value === 'object' ? cur.value : {};
  const groups = Array.isArray(doc.hooks?.SessionStart) ? doc.hooks.SessionStart : [];
  const kept = groups.filter(g => !isOurs(g));
  if (kept.length) doc.hooks.SessionStart = kept;
  else delete doc.hooks?.SessionStart;
  // Only a file that holds nothing but our own mark is removed. Anything else is written back.
  const empty = doc.hooks && Object.keys(doc.hooks).length === 0;
  if (empty && doc.description === MARK) {
    fs.rmSync(file, { force: true });
    return { ok: true, path: file };
  }
  writeAtomic(file, `${JSON.stringify(doc, null, 2)}\n`);
  return { ok: true, path: file };
}

// ---- The three commands ----------------------------------------------------------------------

function summarize(results) {
  const out = { installed: [], failed: [], paths: {} };
  for (const [tool, r] of Object.entries(results)) {
    if (r.ok) out.installed.push(tool); else out.failed.push({ tool, reason: r.reason });
    if (r.path) out.paths[tool] = r.path;
  }
  return out;
}

/** { installed: ['claude','codex'], failed: [{ tool, reason }], paths: { claude, codex } } */
export function installPlugin(opts = {}, version = 'dev') {
  return summarize({ claude: installClaude(opts, version), codex: installCodex(opts) });
}

export function uninstallPlugin(opts = {}) {
  return summarize({ claude: uninstallClaude(opts), codex: uninstallCodex(opts) });
}

export function pluginStatus(opts = {}) {
  const dir = pluginDir(opts);
  const claudeManifest = readJsonFile(path.join(dir, '.claude-plugin', 'plugin.json'));
  const file = codexHooksPath(opts);
  const codexDoc = readJsonFile(file);
  const codexGroups = Array.isArray(codexDoc.value?.hooks?.SessionStart) ? codexDoc.value.hooks.SessionStart : [];
  return {
    claude: { installed: claudeManifest.value?.name === PLUGIN_NAME, path: dir, id: `${PLUGIN_NAME}@skills-dir` },
    codex: { installed: codexGroups.some(isOurs), path: file }
  };
}
