// ============================================================
// shim.mjs — auto-inject gateway env for CLIs launched outside the wrapper
//
// PROBLEM
//   `switch on` writes env.sh and cleans ~/.claude/settings.json (so Claude Code doesn't
//   show the "custom API" banner). Consequence: a `claude` session started from a shell
//   that has NOT sourced env.sh will lack ANTHROPIC_BASE_URL and call
//   api.anthropic.com directly — bypassing the gateway (loses Healer, 1M, pooled quota).
//   Exactly the case of `claude --resume` reopening an old session in a clean shell.
//
// FIX
//   Install executable shims into ~/.llm-switcher/bin/ (placed BEFORE the real binary
//   in PATH). The shim sources env.sh then execs the real binary, so EVERY `claude`
//   /`codex` invocation — including --resume, including from shells without env — goes
//   through the gateway. Doesn't touch settings.json => no banner.
//
// SAFETY
//   - The shim finds the real binary by removing the shim directory itself from PATH,
//     so it never calls itself recursively.
//   - If the gateway is OFF (no active.flag) the shim runs the real binary
//     as-is — no forced routing, no blocking the user.
//   - If the real binary isn't found, the shim reports a clear error instead of staying silent.
// ============================================================

import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { paths, STATE_DIR } from './state.mjs';

export const SHIM_DIR = path.join(os.homedir(), '.llm-switcher', 'bin');

// The shims hand the CA work to Node: reading files, comparing content and renaming atomically
// has no place in a shell script, and none at all in cmd.exe. It is a FILE rather than
// `node -e`, so neither cmd.exe quoting nor URL encoding can corrupt it: pathToFileURL turns a
// space in the checkout into %20, which cmd.exe then reads as the (undefined) argument %2.
const STATE_HELPER = path.join(path.dirname(fileURLToPath(import.meta.url)), 'ensure-ca-bundle.mjs');

// CLIs to wrap. `claude` is the most important case (--resume), codex included for completeness.
export const SHIMMED = ['claude', 'codex'];

// One tool, one env file. Sourcing the shared one is how one tool used to capture the other.
const envFileOf = (name) => (name === 'codex' ? 'env-codex.sh' : 'env-claude.sh');

const POSIX_TEMPLATE = (name) => {
  const envFile = envFileOf(name);
  const caBlock = name === 'codex' ? '' : `
# R2: one bundle holds the user's own CA and the switcher CA, so trusting the interceptor never
# costs a certificate the user already had. Decided here, at launch, because only now is it known
# whether the user brought one — and never while this tool is off.
if [ "$TOOL_ACTIVE" = "1" ]; then
  if [ -z "$INHERITED_CA" ]; then
    if [ -f "$SWITCHER_DIR/blindfold/certs/ca.pem" ]; then
      export NODE_EXTRA_CA_CERTS="$SWITCHER_DIR/blindfold/certs/ca.pem"
    else
      echo "[llm-switcher] $SWITCHER_DIR/blindfold/certs/ca.pem not found; NODE_EXTRA_CA_CERTS kept as inherited." >&2
    fi
  else
    CA_BUNDLE="$(node "$STATE_HELPER" "$INHERITED_CA" "$SWITCHER_DIR/blindfold/certs/ca.pem" "$SWITCHER_DIR")" || CA_BUNDLE=""
    if [ -n "$CA_BUNDLE" ] && [ -f "$CA_BUNDLE" ]; then
      export NODE_EXTRA_CA_CERTS="$CA_BUNDLE"
    fi
  fi
fi`;
  return `#!/usr/bin/env bash
# Auto-generated by LLM Switcher — DO NOT EDIT.
# Hand THIS tool its own gateway env, scrub what an older switcher left behind, then run the real
# "${name}", from any shell — including one that never sourced anything (claude --resume).
SWITCHER_DIR="${STATE_DIR}"
STATE_HELPER="${STATE_HELPER}"
SHIM_DIR="\${BASH_SOURCE%/*}"

# Captured BEFORE the tool's env file is sourced: the CA decision must see the value this shell
# already had, not one this run is about to write.
INHERITED_CA="\${NODE_EXTRA_CA_CERTS:-}"

# Only this tool's own file, only while the gateway is on, and only files this account owns:
# another account could have created the directory or the file. Non-empty means the tool runs;
# an empty file means it is off, and then nothing is sourced at all.
if [ -O "$SWITCHER_DIR" ] && [ -O "$SWITCHER_DIR/${envFile}" ] && [ -f "$SWITCHER_DIR/active.flag" ] && [ -s "$SWITCHER_DIR/${envFile}" ]; then
  . "$SWITCHER_DIR/${envFile}"
  TOOL_ACTIVE=1
else
  TOOL_ACTIVE=0
fi

# R8: a variable is removed ONLY when its value is one an older switcher wrote. The user's own
# proxy, base URL, model or LLM_SWITCHER_* setting is theirs and is kept.
GW_PORT="$( { [ -O "$SWITCHER_DIR/gateway.port" ] && tr -d '[:space:]' < "$SWITCHER_DIR/gateway.port"; } 2>/dev/null )"
case "$GW_PORT" in ''|*[!0-9]*) GW_PORT=3456 ;; esac
PORTS="$GW_PORT 3456"
[ -n "$LLM_SWITCHER_PORT" ] && PORTS="$PORTS $LLM_SWITCHER_PORT"

# Every loopback shape the switcher ever wrote: host, optional /v1, optional trailing slash.
SWITCHER_URLS=""
for _p in $PORTS; do
  for _h in 127.0.0.1 localhost '[::1]'; do
    SWITCHER_URLS="$SWITCHER_URLS $_h:$_p $_h:$_p/ $_h:$_p/v1 $_h:$_p/v1/"
  done
done

_u="\${ANTHROPIC_BASE_URL:-}"
if [ -n "$_u" ]; then
  case " $SWITCHER_URLS " in
    *" \${_u#http://} "*) unset ANTHROPIC_BASE_URL ;;
  esac
fi
_u="\${OPENAI_BASE_URL:-}"
if [ -n "$_u" ]; then
  case " $SWITCHER_URLS " in
    *" \${_u#http://} "*) unset OPENAI_BASE_URL ;;
  esac
fi

# The suffix the old switcher forced on every tier. Nothing else matches: the user's own
# ANTHROPIC_MODEL=opus, or a real model id, is theirs.
case "\${ANTHROPIC_MODEL:-}" in
  opus\\[1m\\]|sonnet\\[1m\\]|haiku\\[1m\\]|fable\\[1m\\]) unset ANTHROPIC_MODEL ;;
esac
tier_is_stale() {
  [ -n "$1" ] || return 1
  case "$(printf '%s' "$1" | tr '[:upper:]' '[:lower:]')" in
    "$2"\\[1m\\]) return 0 ;;
    *) return 1 ;;
  esac
}
if tier_is_stale "$ANTHROPIC_DEFAULT_OPUS_MODEL" opus; then unset ANTHROPIC_DEFAULT_OPUS_MODEL; fi
if tier_is_stale "$ANTHROPIC_DEFAULT_SONNET_MODEL" sonnet; then unset ANTHROPIC_DEFAULT_SONNET_MODEL; fi
if tier_is_stale "$ANTHROPIC_DEFAULT_HAIKU_MODEL" haiku; then unset ANTHROPIC_DEFAULT_HAIKU_MODEL; fi
if tier_is_stale "$ANTHROPIC_DEFAULT_FABLE_MODEL" fable; then unset ANTHROPIC_DEFAULT_FABLE_MODEL; fi

[ "\${CLAUDE_CODE_DISABLE_UNKNOWN_MODEL_WINDOW_ENFORCEMENT:-}" = "1" ] && unset CLAUDE_CODE_DISABLE_UNKNOWN_MODEL_WINDOW_ENFORCEMENT
[ "\${CLAUDE_CODE_AUTO_COMPACT_WINDOW:-}" = "900000" ] && unset CLAUDE_CODE_AUTO_COMPACT_WINDOW
[ "\${OPENAI_MAX_CONTEXT_TOKENS:-}" = "1000000" ] && unset OPENAI_MAX_CONTEXT_TOKENS

# LLM_SWITCHER_CODEX_* was always a shim input, never the user's. Every OTHER LLM_SWITCHER_*
# name is a user setting and is kept.
for _v in $(compgen -v LLM_SWITCHER_CODEX_ 2>/dev/null); do
  unset "$_v"
done
${caBlock}

# Find the real binary: drop the shim directory from PATH so it doesn't call itself.
CLEAN_PATH=""
IFS=':'
for p in $PATH; do
  case "$p" in
    "$SHIM_DIR"|"$SHIM_DIR"/) continue ;;
  esac
  [ -z "$p" ] && continue
  if [ -z "$CLEAN_PATH" ]; then CLEAN_PATH="$p"; else CLEAN_PATH="$CLEAN_PATH:$p"; fi
done
unset IFS

REAL="$(PATH="$CLEAN_PATH" command -v ${name} 2>/dev/null)"
if [ -z "$REAL" ]; then
  echo "[llm-switcher] cannot find the real '${name}' on PATH (\\$SHIM_DIR excluded)." >&2
  echo "[llm-switcher] go shim: switch shim uninstall" >&2
  exit 127
fi

# No override of any kind: the tool keeps its own configuration and its own model names (F3, R1).
exec "$REAL" "$@"
`;
};

const WINDOWS_TEMPLATE = (name) => {
  const envFile = envFileOf(name).replace(/\.sh$/, '.cmd');
  const caBlock = name === 'codex' ? '' : `
REM R2: one bundle holds the user's own CA and the switcher CA, so trusting the interceptor
REM never costs a certificate the user already had. Decided here, at launch, because only now
REM is it known whether the user brought one - and never while this tool is off.
if not "%TOOL_ACTIVE%"=="1" goto :CA_DONE
if defined INHERITED_CA goto :CA_BUNDLE
if exist "%SWITCHER_DIR%\\blindfold\\certs\\ca.pem" set "NODE_EXTRA_CA_CERTS=%SWITCHER_DIR%\\blindfold\\certs\\ca.pem"
if not exist "%SWITCHER_DIR%\\blindfold\\certs\\ca.pem" echo [llm-switcher] %SWITCHER_DIR%\\blindfold\\certs\\ca.pem not found; NODE_EXTRA_CA_CERTS kept as inherited. 1>&2
goto :CA_DONE
:CA_BUNDLE
set "CA_BUNDLE="
for /f "delims=" %%B in ('node "%STATE_HELPER%" "%INHERITED_CA%" "%SWITCHER_DIR%\\blindfold\\certs\\ca.pem" "%SWITCHER_DIR%" 2^>nul') do set "CA_BUNDLE=%%B"
if not defined CA_BUNDLE goto :CA_DONE
if not exist "%CA_BUNDLE%" goto :CA_DONE
set "NODE_EXTRA_CA_CERTS=%CA_BUNDLE%"
:CA_DONE`;
  return `@echo off
REM Auto-generated by LLM Switcher - DO NOT EDIT.
setlocal
set "SWITCHER_DIR=${STATE_DIR}"
${name === 'codex' ? '' : `set "STATE_HELPER=${STATE_HELPER}"

REM Captured BEFORE the tool's env file runs: the CA decision must see the value this shell
REM already had, not one this run is about to write.
set "INHERITED_CA=%NODE_EXTRA_CA_CERTS%"
`}

REM Only this tool's own file, only while the gateway is on, and only a non-empty one: an empty
REM file means this tool is off. The shared env.cmd is never called (F5).
set "TOOL_ACTIVE=0"
if exist "%SWITCHER_DIR%\\active.flag" if exist "%SWITCHER_DIR%\\${envFile}" (
  for %%A in ("%SWITCHER_DIR%\\${envFile}") do if %%~zA GTR 0 set "TOOL_ACTIVE=1"
)
if "%TOOL_ACTIVE%"=="1" call "%SWITCHER_DIR%\\${envFile}"

REM R8: a variable is removed ONLY when its value is one an older switcher wrote. The user's own
REM proxy, base URL, model or LLM_SWITCHER_* setting is theirs and is kept.
set "_GWPORT="
if exist "%SWITCHER_DIR%\\gateway.port" for /f "usebackq delims=" %%P in ("%SWITCHER_DIR%\\gateway.port") do set "_GWPORT=%%P"
if not defined _GWPORT set "_GWPORT=3456"
if defined ANTHROPIC_BASE_URL call :SCRUB_URL ANTHROPIC_BASE_URL "%ANTHROPIC_BASE_URL%"
if defined OPENAI_BASE_URL call :SCRUB_URL OPENAI_BASE_URL "%OPENAI_BASE_URL%"
if /i "%ANTHROPIC_MODEL%"=="opus[1m]" set "ANTHROPIC_MODEL="
if /i "%ANTHROPIC_MODEL%"=="sonnet[1m]" set "ANTHROPIC_MODEL="
if /i "%ANTHROPIC_MODEL%"=="haiku[1m]" set "ANTHROPIC_MODEL="
if /i "%ANTHROPIC_MODEL%"=="fable[1m]" set "ANTHROPIC_MODEL="
if defined ANTHROPIC_DEFAULT_OPUS_MODEL call :SCRUB_TIER ANTHROPIC_DEFAULT_OPUS_MODEL "%ANTHROPIC_DEFAULT_OPUS_MODEL%" opus
if defined ANTHROPIC_DEFAULT_SONNET_MODEL call :SCRUB_TIER ANTHROPIC_DEFAULT_SONNET_MODEL "%ANTHROPIC_DEFAULT_SONNET_MODEL%" sonnet
if defined ANTHROPIC_DEFAULT_HAIKU_MODEL call :SCRUB_TIER ANTHROPIC_DEFAULT_HAIKU_MODEL "%ANTHROPIC_DEFAULT_HAIKU_MODEL%" haiku
if defined ANTHROPIC_DEFAULT_FABLE_MODEL call :SCRUB_TIER ANTHROPIC_DEFAULT_FABLE_MODEL "%ANTHROPIC_DEFAULT_FABLE_MODEL%" fable
if "%CLAUDE_CODE_DISABLE_UNKNOWN_MODEL_WINDOW_ENFORCEMENT%"=="1" set "CLAUDE_CODE_DISABLE_UNKNOWN_MODEL_WINDOW_ENFORCEMENT="
if "%CLAUDE_CODE_AUTO_COMPACT_WINDOW%"=="900000" set "CLAUDE_CODE_AUTO_COMPACT_WINDOW="
if "%OPENAI_MAX_CONTEXT_TOKENS%"=="1000000" set "OPENAI_MAX_CONTEXT_TOKENS="
for /f "tokens=1 delims==" %%V in ('set LLM_SWITCHER_CODEX_ 2^>nul ^| findstr /b /c:"LLM_SWITCHER_CODEX_"') do set "%%V="
${caBlock}

REM Find the real binary: drop this shim's own directory so it never calls itself.
for /f "delims=" %%i in ('where ${name}.cmd 2^>nul ^| findstr /v /i "\\.llm-switcher\\\\bin"') do (
  call "%%i" %*
  exit /b
)
for /f "delims=" %%i in ('where ${name}.exe 2^>nul ^| findstr /v /i "\\.llm-switcher\\\\bin"') do (
  call "%%i" %*
  exit /b
)
echo [llm-switcher] cannot find the real '${name}' on PATH.>&2
exit /b 127

REM ---- R8 subroutines ----------------------------------------------------

REM %1 = variable name, %2 = its value. Unsets %1 only for a loopback gateway URL on a port this
REM switcher has used: the recorded one, the default 3456, or LLM_SWITCHER_PORT.
:SCRUB_URL
set "_T=%~2"
if /i "%_T:~0,7%"=="http://" set "_T=%_T:~7%"
set "_R="
if /i "%_T:~0,10%"=="127.0.0.1:" set "_R=%_T:~10%"
if /i "%_T:~0,10%"=="localhost:" set "_R=%_T:~10%"
if /i "%_T:~0,6%"=="[::1]:" set "_R=%_T:~6%"
if not defined _R goto :eof
if /i "%_R:~-4%"=="/v1/" set "_R=%_R:~0,-4%"
if /i "%_R:~-3%"=="/v1" set "_R=%_R:~0,-3%"
if "%_R:~-1%"=="/" set "_R=%_R:~0,-1%"
if not defined _R goto :eof
if not "%_R%"=="" for /f "delims=0123456789" %%X in ("%_R%") do goto :eof
if "%_R%"=="%_GWPORT%" goto :DROP_URL
if "%_R%"=="3456" goto :DROP_URL
if defined LLM_SWITCHER_PORT if "%_R%"=="%LLM_SWITCHER_PORT%" goto :DROP_URL
goto :eof
:DROP_URL
set "%~1="
goto :eof

REM %1 = variable name, %2 = its value, %3 = the lowercase tier it must still match. A value of
REM another tier (ANTHROPIC_DEFAULT_OPUS_MODEL=sonnet[1m]) is not the switcher's and is kept.
:SCRUB_TIER
if /i "%~2"=="%~3[1m]" set "%~1="
goto :eof
`;
};

export function renderShim(name, platform = process.platform) {
  if (platform !== 'win32') return POSIX_TEMPLATE(name);
  // cmd.exe finds a subroutine by scanning line starts, and on a file written with bare LF
  // it drifts: a label near the end is reported as "cannot find the batch label". CRLF is
  // what every .cmd on disk already is, and it is what cmd.exe expects.
  return WINDOWS_TEMPLATE(name).replace(/\r?\n/g, '\r\n');
}

function shimPath(name) {
  return path.join(SHIM_DIR, process.platform === 'win32' ? `${name}.cmd` : name);
}

/** Install shims for the CLIs. Returns {installed:[], skipped:[], error?} */
export function installShims(names = SHIMMED) {
  try {
    fs.mkdirSync(SHIM_DIR, { recursive: true });
  } catch (err) {
    return { installed: [], skipped: [], error: `cannot create ${SHIM_DIR}: ${err.message}` };
  }

  const installed = [];
  const skipped = [];
  for (const name of names) {
    const target = shimPath(name);
    const body = renderShim(name);
    try {
      // Don't overwrite unfamiliar files created by the user.
      if (fs.existsSync(target)) {
        const cur = fs.readFileSync(target, 'utf8');
        if (!cur.includes('Auto-generated by LLM Switcher')) {
          skipped.push({ name, reason: 'a file that is not a switcher shim already exists there' });
          continue;
        }
      }
      fs.writeFileSync(target, body, 'utf8');
      if (process.platform !== 'win32') fs.chmodSync(target, 0o755);
      installed.push(name);
    } catch (err) {
      skipped.push({ name, reason: err.message });
    }
  }
  return { installed, skipped };
}

export function uninstallShims(names = SHIMMED) {
  const removed = [];
  const failed = [];
  for (const name of names) {
    const target = shimPath(name);
    try {
      if (!fs.existsSync(target)) continue;
      const cur = fs.readFileSync(target, 'utf8');
      if (!cur.includes('Auto-generated by LLM Switcher')) continue;
      fs.unlinkSync(target);
      removed.push(name);
    } catch (err) {
      failed.push({ name, reason: err.message });
    }
  }
  return { removed, failed };
}

/** Is SHIM_DIR already ahead of the real binary in PATH? */
export function shimStatus(names = SHIMMED) {
  const entries = (process.env.PATH || '').split(path.delimiter).filter(Boolean);
  const idx = entries.findIndex(p => path.resolve(p) === path.resolve(SHIM_DIR));
  const out = { dir: SHIM_DIR, onPath: idx !== -1, position: idx, shims: [] };

  for (const name of names) {
    const target = shimPath(name);
    const exists = fs.existsSync(target);
    let effective = null;   // which binary will run when the command name is typed
    for (const p of entries) {
      const cand = path.join(p, process.platform === 'win32' ? `${name}.cmd` : name);
      const candExe = path.join(p, name);
      if (fs.existsSync(cand)) { effective = cand; break; }
      if (fs.existsSync(candExe)) { effective = candExe; break; }
    }
    out.shims.push({
      name,
      installed: exists,
      effective,
      active: exists && effective !== null && path.resolve(effective) === path.resolve(target)
    });
  }
  return out;
}

/** Line to add to the shell rc so the shim comes before the real binary. */
// Windows: setx truncates at 1024 characters and would copy the merged system+user PATH into the
// user key, and PowerShell does not expand %PATH%. Prepend to the User-scope Path only.
export function pathExportLine(platform = process.platform) {
  if (platform === 'win32') {
    return `powershell -NoProfile -Command "[Environment]::SetEnvironmentVariable('Path', '${SHIM_DIR};' + [Environment]::GetEnvironmentVariable('Path', 'User'), 'User')"`;
  }
  return `export PATH="${SHIM_DIR}:$PATH"`;
}

/** Which rc file to edit, based on the current shell. Windows has none: the command above is run once. */
export function suggestedRcFiles(platform = process.platform) {
  if (platform === 'win32') return [];
  const home = os.homedir();
  const shell = path.basename(process.env.SHELL || '');
  if (shell === 'zsh') return [path.join(home, '.zshrc'), path.join(home, '.zprofile')];
  if (shell === 'bash') return [path.join(home, '.bashrc'), path.join(home, '.bash_profile')];
  return [path.join(home, '.profile')];
}

// The shim is on PATH but behind the real binary: a line that runs later prepends another directory
// (npm-global, Homebrew). Login shells read the profile file, interactive shells the rc file.
export function pathOrderHint(platform = process.platform) {
  const files = suggestedRcFiles(platform);
  if (!files.length) return [`Run this command, then open a new terminal: ${pathExportLine(platform)}`];
  return [`Put this line LAST in ${files.join(' and ')}, after every other PATH line, then open a new terminal:`,
    `    ${pathExportLine(platform)}`];
}

/**
 * Check whether running CLI processes have the gateway env.
 * This is the hardest failure to spot: a `claude` session opened BEFORE the gateway
 * was enabled (or from a shell that hasn't sourced env.sh) will call api.anthropic.com
 * directly. The shim intercepts NEW sessions, but live processes must be detected and reported so they can be restarted.
 */
// What in a process's command line and environment shows that it goes through the gateway.
// Codex takes the gateway URL as a --config override, or the interceptor as HTTPS_PROXY.
const ROUTE_EVIDENCE = {
  claude: /(^|\s)ANTHROPIC_BASE_URL=/,
  codex: /(^|\s)(LLM_SWITCHER_CODEX_BASE_URL=|https?_proxy=http:\/\/(127\.0\.0\.1|localhost)[:/]|openai_base_url=http:\/\/(127\.0\.0\.1|localhost)[:/])/i
};

/** true | false, or null when the dump holds no environment (macOS ps for most processes). */
export function routeEvidence(name, envDump) {
  // The shim's own `--config key=value` arguments look like variables; only the rest can be environment.
  if (ROUTE_EVIDENCE[name].test(envDump)) return true;
  const rest = envDump.replace(/(^|\s)(--config|-c)\s+\S+/g, ' ');
  return /\s[A-Za-z_][A-Za-z0-9_]*=/.test(rest) ? false : null;
}

// `names` are the CLIs whose target is active: a CLI whose target is off uses the official endpoint
// on purpose, so a missing gateway variable there is not a bypass.
export function auditRunningProcesses(names = SHIMMED) {
  if (process.platform === 'win32') return { supported: false, procs: [] };
  const procs = [];
  try {
    // Get pid + command of the CLIs of interest (excluding the pgrep/grep command itself).
    const pattern = names.join('|');
    const listed = execFileSync('pgrep', ['-f', `(${pattern})`], { encoding: 'utf8' })
      .split('\n').map(s => s.trim()).filter(Boolean);

    for (const pid of listed) {
      let cmd = '';
      try {
        cmd = execFileSync('ps', ['-p', pid, '-o', 'command='], { encoding: 'utf8' }).trim();
      } catch { continue; }
      if (!cmd) continue;
      // Keep only processes that are actually the CLI under check, skip helper processes.
      if (!names.some(n => new RegExp(`(^|/|\\s)${n}(\\s|$)`).test(cmd))) continue;
      if (/pgrep|llm-switcher\/(switch|proxy)\.mjs/.test(cmd)) continue;

      const name = names.find(n => new RegExp(`(^|/|\\s)${n}(\\s|$)`).test(cmd));
      let hasEnv = null;  // null = cannot read that process's env
      try {
        // `ps eww` appends the environment, but only for processes this account may read.
        hasEnv = routeEvidence(name, execFileSync('ps', ['eww', '-p', pid, '-o', 'command='], { encoding: 'utf8' }));
      } catch {}
      procs.push({ pid, name, cmd: cmd.slice(0, 90), hasEnv });
    }
  } catch {
    // pgrep returns a non-zero exit code when there are no processes — not an error.
  }
  return { supported: true, procs };
}

export { paths };
