// ============================================================
// shim.mjs — auto-inject gateway env cho CLI khởi chạy ngoài wrapper
//
// VẤN ĐỀ
//   `switch on` ghi env.sh và dọn ~/.claude/settings.json (để Claude Code không
//   hiện banner "custom API"). Hệ quả: một phiên `claude` khởi chạy từ shell
//   CHƯA source env.sh sẽ không có ANTHROPIC_BASE_URL và gọi thẳng
//   api.anthropic.com — bỏ qua gateway (mất Healer, 1M, pooled quota).
//   Đúng trường hợp `claude --resume` mở lại phiên cũ trong shell sạch.
//
// CÁCH CHỮA
//   Cài shim thực thi vào ~/.llm-switcher/bin/ (đứng TRƯỚC binary thật trong
//   PATH). Shim source env.sh rồi exec binary thật, nên MỌI lần gọi `claude`
//   /`codex` — kể cả --resume, kể cả từ shell không có env — đều qua gateway.
//   Không đụng settings.json => không banner.
//
// AN TOÀN
//   - Shim tự tìm binary thật bằng cách loại chính thư mục shim khỏi PATH,
//     nên không bao giờ gọi đệ quy chính nó.
//   - Nếu gateway đang TẮT (không có active.flag) shim chạy binary thật
//     nguyên trạng — không ép route, không chặn người dùng.
//   - Nếu không tìm thấy binary thật, shim báo lỗi rõ thay vì im lặng.
// ============================================================

import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { execFileSync } from 'node:child_process';
import { paths, ROOT_DIR } from './state.mjs';

export const SHIM_DIR = path.join(os.homedir(), '.llm-switcher', 'bin');

// CLI cần bọc. `claude` là ca quan trọng nhất (--resume), codex đi kèm cho đủ bộ.
export const SHIMMED = ['claude', 'codex'];

const POSIX_TEMPLATE = (name) => `#!/usr/bin/env bash
# Auto-generated by LLM Switcher — DO NOT EDIT.
# Nạp env gateway rồi chạy "${name}" thật, kể cả khi shell chưa source env.sh
# (ví dụ: claude --resume mở lại phiên cũ trong terminal sạch).
SWITCHER_DIR="${ROOT_DIR}"
SHIM_DIR="\${BASH_SOURCE%/*}"

# Chỉ nạp env khi gateway đang bật; tắt thì để CLI chạy nguyên trạng.
if [ -f "$SWITCHER_DIR/active.flag" ] && [ -f "$SWITCHER_DIR/env.sh" ]; then
  . "$SWITCHER_DIR/env.sh"
fi

# Tìm binary thật: bỏ thư mục shim khỏi PATH để không tự gọi lại chính mình.
CLEAN_PATH=""
IFS=':'
for p in $PATH; do
  case "$p" in
    "$SHIM_DIR"|"$SHIM_DIR"/) continue ;;
  esac
  [ -z "$p" ] && continue
  if [ -z "$CLEAN_PATH" ]; then CLEAN_PATH="$p"; else CLEAN_PATH="$CLEAN_PATH:$p"; fi
done
unset IFS

REAL="$(PATH="$CLEAN_PATH" command -v ${name} 2>/dev/null)"
if [ -z "$REAL" ]; then
  echo "[llm-switcher] khong tim thay '${name}' that trong PATH (da loai \\$SHIM_DIR)." >&2
  echo "[llm-switcher] go shim: switch shim uninstall" >&2
  exit 127
fi

exec "$REAL" "$@"
`;

const WINDOWS_TEMPLATE = (name) => `@echo off
REM Auto-generated by LLM Switcher — DO NOT EDIT.
setlocal
set "SWITCHER_DIR=${ROOT_DIR}"
if exist "%SWITCHER_DIR%\\active.flag" if exist "%SWITCHER_DIR%\\env.cmd" call "%SWITCHER_DIR%\\env.cmd"
endlocal & set "ANTHROPIC_BASE_URL=%ANTHROPIC_BASE_URL%"
for /f "delims=" %%i in ('where ${name} 2^>nul ^| findstr /v /i "\\.llm-switcher\\\\bin"') do (
  "%%i" %*
  exit /b %errorlevel%
)
echo [llm-switcher] khong tim thay '${name}' that trong PATH.>&2
exit /b 127
`;

function shimPath(name) {
  return path.join(SHIM_DIR, process.platform === 'win32' ? `${name}.cmd` : name);
}

/** Cài shim cho các CLI. Trả về {installed:[], skipped:[], error?} */
export function installShims(names = SHIMMED) {
  try {
    fs.mkdirSync(SHIM_DIR, { recursive: true });
  } catch (err) {
    return { installed: [], skipped: [], error: `khong tao duoc ${SHIM_DIR}: ${err.message}` };
  }

  const installed = [];
  const skipped = [];
  for (const name of names) {
    const target = shimPath(name);
    const body = process.platform === 'win32' ? WINDOWS_TEMPLATE(name) : POSIX_TEMPLATE(name);
    try {
      // Không đè file lạ do người dùng tự tạo.
      if (fs.existsSync(target)) {
        const cur = fs.readFileSync(target, 'utf8');
        if (!cur.includes('Auto-generated by LLM Switcher')) {
          skipped.push({ name, reason: 'file da ton tai va khong phai shim cua switcher' });
          continue;
        }
      }
      fs.writeFileSync(target, body, 'utf8');
      if (process.platform !== 'win32') fs.chmodSync(target, 0o755);
      installed.push(name);
    } catch (err) {
      skipped.push({ name, reason: err.message });
    }
  }
  return { installed, skipped };
}

export function uninstallShims(names = SHIMMED) {
  const removed = [];
  for (const name of names) {
    const target = shimPath(name);
    try {
      if (!fs.existsSync(target)) continue;
      const cur = fs.readFileSync(target, 'utf8');
      if (!cur.includes('Auto-generated by LLM Switcher')) continue;
      fs.unlinkSync(target);
      removed.push(name);
    } catch {}
  }
  return { removed };
}

/** SHIM_DIR đã nằm trước binary thật trong PATH chưa? */
export function shimStatus(names = SHIMMED) {
  const entries = (process.env.PATH || '').split(path.delimiter).filter(Boolean);
  const idx = entries.findIndex(p => path.resolve(p) === path.resolve(SHIM_DIR));
  const out = { dir: SHIM_DIR, onPath: idx !== -1, position: idx, shims: [] };

  for (const name of names) {
    const target = shimPath(name);
    const exists = fs.existsSync(target);
    let effective = null;   // binary nào sẽ chạy khi gõ tên lệnh
    for (const p of entries) {
      const cand = path.join(p, process.platform === 'win32' ? `${name}.cmd` : name);
      const candExe = path.join(p, name);
      if (fs.existsSync(cand)) { effective = cand; break; }
      if (fs.existsSync(candExe)) { effective = candExe; break; }
    }
    out.shims.push({
      name,
      installed: exists,
      effective,
      active: exists && effective !== null && path.resolve(effective) === path.resolve(target)
    });
  }
  return out;
}

/** Dòng cần thêm vào shell rc để shim đứng trước binary thật. */
export function pathExportLine() {
  return process.platform === 'win32'
    ? `setx PATH "${SHIM_DIR};%PATH%"`
    : `export PATH="${SHIM_DIR}:$PATH"`;
}

/** File rc nên sửa, theo shell đang dùng. */
export function suggestedRcFiles() {
  const home = os.homedir();
  const shell = path.basename(process.env.SHELL || '');
  if (shell === 'zsh') return [path.join(home, '.zshrc'), path.join(home, '.zprofile')];
  if (shell === 'bash') return [path.join(home, '.bashrc'), path.join(home, '.bash_profile')];
  return [path.join(home, '.profile')];
}

/**
 * Kiểm tra các process CLI đang chạy có env gateway không.
 * Đây là ca hỏng khó thấy nhất: phiên `claude` mở TRƯỚC khi bật gateway (hoặc
 * từ shell chưa source env.sh) sẽ gọi thẳng api.anthropic.com. Shim chặn được
 * phiên MỚI, nhưng process đang sống thì phải phát hiện và báo để mở lại.
 */
export function auditRunningProcesses(names = SHIMMED) {
  if (process.platform === 'win32') return { supported: false, procs: [] };
  const procs = [];
  try {
    // Lấy pid + command của các CLI quan tâm (bỏ chính lệnh pgrep/grep).
    const pattern = names.join('|');
    const listed = execFileSync('pgrep', ['-f', `(${pattern})`], { encoding: 'utf8' })
      .split('\n').map(s => s.trim()).filter(Boolean);

    for (const pid of listed) {
      let cmd = '';
      try {
        cmd = execFileSync('ps', ['-p', pid, '-o', 'command='], { encoding: 'utf8' }).trim();
      } catch { continue; }
      if (!cmd) continue;
      // Chỉ giữ process thực sự là CLI cần kiểm, bỏ tiến trình phụ trợ.
      if (!names.some(n => new RegExp(`(^|/|\\s)${n}(\\s|$)`).test(cmd))) continue;
      if (/pgrep|llm-switcher\/(switch|proxy)\.mjs/.test(cmd)) continue;

      let hasEnv = null;  // null = không đọc được env của process đó
      try {
        // `ps eww` in kèm environ; chỉ chạy được với process của chính user.
        const envDump = execFileSync('ps', ['eww', '-p', pid, '-o', 'command='], { encoding: 'utf8' });
        hasEnv = /ANTHROPIC_BASE_URL=/.test(envDump);
      } catch {}
      procs.push({ pid, cmd: cmd.slice(0, 90), hasEnv });
    }
  } catch {
    // pgrep trả mã != 0 khi không có process nào — không phải lỗi.
  }
  return { supported: true, procs };
}

export { paths };
